apiVersion: v1
kind: Service
metadata:
    labels:
        app: cookalone-web
    name: cookalone-web
    namespace: cookalone-web
spec:
    ports:
    - name: cookalone-web
      port: 8080
      targetPort: 8080
    selector:
      app: cookalone-web
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: cookalone-web
    name: cookalone-web
    namespace: cookalone-web
spec:
    selector:
        matchLabels:
            app: cookalone-web
    template:
        metadata:
            labels:
                app: cookalone-web
        spec:
            containers:
            - image: 128324953611.dkr.ecr.ap-northeast-2.amazonaws.com/cookalone-dev-ecr:11 #{{ .Values.cookalone-web.image }}
              imagePullPolicy: Always
              name: cookalone-web
              ports:
              - containerPort: 8080