apiVersion: v1
kind: Service
metadata:
    labels:
        app: cookalone-web
    name: cookalone-web
    namespace: cookalone-web
spec:
    ports:
    - name: cookalone-web
      port: 80
      targetPort: 8080
    selector:
      app: cookalone-web
    type: NodePort #LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: cookalone-web
    name: cookalone-web
    namespace: cookalone-web
spec:
    selector:
        matchLabels:
            app: cookalone-web
    template:
        metadata:
            labels:
                app: cookalone-web
        spec:
            containers:
            - image: {{ .Values.cookalone.image }}
              imagePullPolicy: Always
              name: cookalone-web
              ports:
              - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cookalone-ingress
  namespace: cookalone-web
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-077eef7b3477306c6, subnet-07cd7d4887d258afd
    alb.ingress.kubernetes.io/target-type: instance
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "cookalone-web"
                port:
                  number: 80